spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ---
            client-secret: ---

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

mail:
  host: "localhost"
  port: 1025
  username: "mobilele@mobilele.com"
  password: ""

  server:
    port: ${PORT:8080}